(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un209');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-284-52.php':'images/transparentks-142-82.php');
var a='data-src';var e=document.querySelector('.un210');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-28.php':'images/k-stransparent-424-58.php');
var e=document.querySelector('.un204');e.setAttribute('src',(dpi>1)?'images/transparentks-284-50.php':'images/transparentks-142-78.php');
var e=document.querySelector('.un205');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-28.php':'images/k-stransparent-424-58.php');
var e=document.querySelector('.un206');e.setAttribute('src',(dpi>1)?'images/csi-logo-272-26.php':'images/csi-logo-136-54.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un209');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-178-60.php':'images/transparentks-89-60.php');
var a='data-src';var e=document.querySelector('.un210');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-28.php':'images/k-stransparent-265-28.php');
var e=document.querySelector('.un204');e.setAttribute('src',(dpi>1)?'images/transparentks-178-58.php':'images/transparentks-89-58.php');
var e=document.querySelector('.un205');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-28.php':'images/k-stransparent-265-28.php');
var e=document.querySelector('.un206');e.setAttribute('src',(dpi>1)?'images/csi-logo-170-26.php':'images/csi-logo-85-26.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un209');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-142-80.php':'images/transparentks-71-28.php');
var a='data-src';var e=document.querySelector('.un210');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-424-56.php':'images/k-stransparent-212-28.php');
var e=document.querySelector('.un204');e.setAttribute('src',(dpi>1)?'images/transparentks-138-22.php':'images/transparentks-69-22.php');
var e=document.querySelector('.un205');e.setAttribute('src',(dpi>1)?'images/k-stransparent-424-56.php':'images/k-stransparent-212-28.php');
var e=document.querySelector('.un206');e.setAttribute('src',(dpi>1)?'images/csi-logo-136-52.php':'images/csi-logo-68-26.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un209');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-114-32.php':'images/transparentks-57-32.php');
var a='data-src';var e=document.querySelector('.un210');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-340-26.php':'images/k-stransparent-170-26.php');
var e=document.querySelector('.un204');e.setAttribute('src',(dpi>1)?'images/transparentks-110-22.php':'images/transparentks-55-22.php');
var e=document.querySelector('.un205');e.setAttribute('src',(dpi>1)?'images/k-stransparent-340-26.php':'images/k-stransparent-170-26.php');
var e=document.querySelector('.un206');e.setAttribute('src',(dpi>1)?'images/csi-logo-108-26.php':'images/csi-logo-54-26.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un209');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-306-28.php':'images/transparentks-153-28.php');
var a='data-src';var e=document.querySelector('.un210');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-330-28.php':'images/k-stransparent-165-28.php');
var e=document.querySelector('.un204');e.setAttribute('src',(dpi>1)?'images/transparentks-192-28.php':'images/transparentks-96-28.php');
var e=document.querySelector('.un205');e.setAttribute('src',(dpi>1)?'images/k-stransparent-392-20.php':'images/k-stransparent-196-20.php');
var e=document.querySelector('.un206');e.setAttribute('src',(dpi>1)?'images/csi-logo-174-20.php':'images/csi-logo-87-20.php');}else{var a='data-src';var e=document.querySelector('.un209');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-204-28.php':'images/transparentks-102-28.php');
var a='data-src';var e=document.querySelector('.un210');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-220-28.php':'images/k-stransparent-110-28.php');
var e=document.querySelector('.un204');e.setAttribute('src',(dpi>1)?'images/transparentks-128-28.php':'images/transparentks-64-28.php');
var e=document.querySelector('.un205');e.setAttribute('src',(dpi>1)?'images/k-stransparent-262-20.php':'images/k-stransparent-131-20.php');
var e=document.querySelector('.un206');e.setAttribute('src',(dpi>1)?'images/csi-logo-116-20.php':'images/csi-logo-58-20.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un207=new Plyr('.un207 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un207.volume=0.8;
un208=new Plyr('.un208 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un208.volume=0.8;
initMenu($('#m3')[0]);
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un246 source');ldsrcset('.un247 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}