(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/teams-300-4.php':'images/teams-150-4.php');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-190-10.php');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-190-10.php');
var a='data-src';var e=document.querySelector('.un41');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-190-10.php');
var a='data-src';var e=document.querySelector('.un42');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-190-10.php');
var a='data-src';var e=document.querySelector('.un43');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-190-10.php');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-190-10.php');
var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-190-10.php');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-190-10.php');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-190-10.php');
var a='data-src';var e=document.querySelector('.un48');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-190-10.php');
var a='data-src';var e=document.querySelector('.un49');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-190-10.php');
var a='data-src';var e=document.querySelector('.un50');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-190-10.php');
var a='data-src';var e=document.querySelector('.un51');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-190-10.php');
var a='data-src';var e=document.querySelector('.un52');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-190-10.php');
var a='data-src';var e=document.querySelector('.un53');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-190-10.php');
var a='data-src';var e=document.querySelector('.un54');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-190-10.php');
var a='data-src';var e=document.querySelector('.un55');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-190-10.php');
var a='data-src';var e=document.querySelector('.un56');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-284-48.php':'images/transparentks-142-76.php');
var a='data-src';var e=document.querySelector('.un57');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-26.php':'images/k-stransparent-424-54.php');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'images/transparentks-284-46.php':'images/transparentks-142-72.php');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-26.php':'images/k-stransparent-424-54.php');
var e=document.querySelector('.un35');e.setAttribute('src',(dpi>1)?'images/csi-logo-272-24.php':'images/csi-logo-136-50.php');
var e=document.querySelector('.un36');e.setAttribute('src','images/preliminary_program_csi_2022-1656-4.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/teams-188-4.php':'images/teams-94-4.php');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-119-4.php');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-119-4.php');
var a='data-src';var e=document.querySelector('.un41');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-119-4.php');
var a='data-src';var e=document.querySelector('.un42');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-119-4.php');
var a='data-src';var e=document.querySelector('.un43');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-119-4.php');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-119-4.php');
var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-119-4.php');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-119-4.php');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-119-4.php');
var a='data-src';var e=document.querySelector('.un48');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-119-4.php');
var a='data-src';var e=document.querySelector('.un49');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-119-4.php');
var a='data-src';var e=document.querySelector('.un50');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-119-4.php');
var a='data-src';var e=document.querySelector('.un51');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-119-4.php');
var a='data-src';var e=document.querySelector('.un52');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-119-4.php');
var a='data-src';var e=document.querySelector('.un53');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-119-4.php');
var a='data-src';var e=document.querySelector('.un54');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-119-4.php');
var a='data-src';var e=document.querySelector('.un55');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-119-4.php');
var a='data-src';var e=document.querySelector('.un56');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-178-56.php':'images/transparentks-89-56.php');
var a='data-src';var e=document.querySelector('.un57');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-26.php':'images/k-stransparent-265-26.php');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'images/transparentks-178-54.php':'images/transparentks-89-54.php');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-26.php':'images/k-stransparent-265-26.php');
var e=document.querySelector('.un35');e.setAttribute('src',(dpi>1)?'images/csi-logo-170-24.php':'images/csi-logo-85-24.php');
var e=document.querySelector('.un36');e.setAttribute('src','images/preliminary_program_csi_2022-1035-4.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/teams-154-4.php':'images/teams-77-4.php');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/enise-190-8.php':'images/enise-95-4.php');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ensam-190-8.php':'images/ensam-95-4.php');
var a='data-src';var e=document.querySelector('.un41');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ltds-190-8.php':'images/ltds-95-4.php');
var a='data-src';var e=document.querySelector('.un42');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/mrx_rays-190-8.php':'images/mrx_rays-95-4.php');
var a='data-src';var e=document.querySelector('.un43');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fives-190-8.php':'images/fives-95-4.php');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digitalsurf-190-8.php':'images/digitalsurf-95-4.php');
var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/brukeralicona-190-8.php':'images/brukeralicona-95-4.php');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/clubusinageinnovation-190-8.php':'images/clubusinageinnovation-95-4.php');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ingelyse-190-8.php':'images/ingelyse-95-4.php');
var a='data-src';var e=document.querySelector('.un48');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fondation_enise-190-8.php':'images/fondation_enise-95-4.php');
var a='data-src';var e=document.querySelector('.un49');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/labex_manutech-190-8.php':'images/labex_manutech-95-4.php');
var a='data-src';var e=document.querySelector('.un50');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/institut_carnot-190-8.php':'images/institut_carnot-95-4.php');
var a='data-src';var e=document.querySelector('.un51');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/laregionaura-190-8.php':'images/laregionaura-95-4.php');
var a='data-src';var e=document.querySelector('.un52');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cnrs-190-8.php':'images/cnrs-95-4.php');
var a='data-src';var e=document.querySelector('.un53');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/onlylyon-190-8.php':'images/onlylyon-95-4.php');
var a='data-src';var e=document.querySelector('.un54');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/centraleinnovation-190-8.php':'images/centraleinnovation-95-4.php');
var a='data-src';var e=document.querySelector('.un55');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/tivoly-190-8.php':'images/tivoly-95-4.php');
var a='data-src';var e=document.querySelector('.un56');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-142-74.php':'images/transparentks-71-26.php');
var a='data-src';var e=document.querySelector('.un57');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-424-52.php':'images/k-stransparent-212-26.php');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'images/transparentks-138-20.php':'images/transparentks-69-20.php');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'images/k-stransparent-424-52.php':'images/k-stransparent-212-26.php');
var e=document.querySelector('.un35');e.setAttribute('src',(dpi>1)?'images/csi-logo-136-48.php':'images/csi-logo-68-24.php');
var e=document.querySelector('.un36');e.setAttribute('src','images/preliminary_program_csi_2022-828-10.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/teams-122-4.php':'images/teams-61-4.php');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/enise-152-4.php':'images/enise-76-4.php');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ensam-152-4.php':'images/ensam-76-4.php');
var a='data-src';var e=document.querySelector('.un41');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ltds-152-4.php':'images/ltds-76-4.php');
var a='data-src';var e=document.querySelector('.un42');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/mrx_rays-152-4.php':'images/mrx_rays-76-4.php');
var a='data-src';var e=document.querySelector('.un43');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fives-152-4.php':'images/fives-76-4.php');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digitalsurf-152-4.php':'images/digitalsurf-76-4.php');
var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/brukeralicona-152-4.php':'images/brukeralicona-76-4.php');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/clubusinageinnovation-152-4.php':'images/clubusinageinnovation-76-4.php');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ingelyse-152-4.php':'images/ingelyse-76-4.php');
var a='data-src';var e=document.querySelector('.un48');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fondation_enise-152-4.php':'images/fondation_enise-76-4.php');
var a='data-src';var e=document.querySelector('.un49');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/labex_manutech-152-4.php':'images/labex_manutech-76-4.php');
var a='data-src';var e=document.querySelector('.un50');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/institut_carnot-152-4.php':'images/institut_carnot-76-4.php');
var a='data-src';var e=document.querySelector('.un51');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/laregionaura-152-4.php':'images/laregionaura-76-4.php');
var a='data-src';var e=document.querySelector('.un52');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cnrs-152-4.php':'images/cnrs-76-4.php');
var a='data-src';var e=document.querySelector('.un53');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/onlylyon-152-4.php':'images/onlylyon-76-4.php');
var a='data-src';var e=document.querySelector('.un54');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/centraleinnovation-152-4.php':'images/centraleinnovation-76-4.php');
var a='data-src';var e=document.querySelector('.un55');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/tivoly-152-4.php':'images/tivoly-76-4.php');
var a='data-src';var e=document.querySelector('.un56');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-114-30.php':'images/transparentks-57-30.php');
var a='data-src';var e=document.querySelector('.un57');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-340-24.php':'images/k-stransparent-170-24.php');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'images/transparentks-110-20.php':'images/transparentks-55-20.php');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'images/k-stransparent-340-24.php':'images/k-stransparent-170-24.php');
var e=document.querySelector('.un35');e.setAttribute('src',(dpi>1)?'images/csi-logo-108-24.php':'images/csi-logo-54-24.php');
var e=document.querySelector('.un36');e.setAttribute('src','images/preliminary_program_csi_2022-662-4.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/teams-294-4.php':'images/teams-147-4.php');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-242-4.php');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-237-4.php');
var a='data-src';var e=document.querySelector('.un41');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-236-4.php');
var a='data-src';var e=document.querySelector('.un42');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-237-4.php');
var a='data-src';var e=document.querySelector('.un43');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-242-4.php');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-236-4.php');
var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-240-4.php');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-240-4.php');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-243-4.php');
var a='data-src';var e=document.querySelector('.un48');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-244-4.php');
var a='data-src';var e=document.querySelector('.un49');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-244-4.php');
var a='data-src';var e=document.querySelector('.un50');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-230-4.php');
var a='data-src';var e=document.querySelector('.un51');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-236-4.php');
var a='data-src';var e=document.querySelector('.un52');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-232-4.php');
var a='data-src';var e=document.querySelector('.un53');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-231-4.php');
var a='data-src';var e=document.querySelector('.un54');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-238-4.php');
var a='data-src';var e=document.querySelector('.un55');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-232-4.php');
var a='data-src';var e=document.querySelector('.un56');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-306-26.php':'images/transparentks-153-26.php');
var a='data-src';var e=document.querySelector('.un57');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-330-26.php':'images/k-stransparent-165-26.php');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'images/transparentks-192-26.php':'images/transparentks-96-26.php');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'images/k-stransparent-392-18.php':'images/k-stransparent-196-18.php');
var e=document.querySelector('.un35');e.setAttribute('src',(dpi>1)?'images/csi-logo-174-18.php':'images/csi-logo-87-18.php');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'images/preliminary_program_csi_2022-828-8.php':'images/preliminary_program_csi_2022-414-4.php');}else{var a='data-src';var e=document.querySelector('.un37');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/teams-196-4.php':'images/teams-98-4.php');
var a='data-src';var e=document.querySelector('.un39');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-161-4.php');
var a='data-src';var e=document.querySelector('.un40');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-158-4.php');
var a='data-src';var e=document.querySelector('.un41');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-157-4.php');
var a='data-src';var e=document.querySelector('.un42');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-158-4.php');
var a='data-src';var e=document.querySelector('.un43');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-161-4.php');
var a='data-src';var e=document.querySelector('.un44');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-157-4.php');
var a='data-src';var e=document.querySelector('.un45');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-160-4.php');
var a='data-src';var e=document.querySelector('.un46');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-160-4.php');
var a='data-src';var e=document.querySelector('.un47');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-162-4.php');
var a='data-src';var e=document.querySelector('.un48');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-163-4.php');
var a='data-src';var e=document.querySelector('.un49');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-163-4.php');
var a='data-src';var e=document.querySelector('.un50');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-154-4.php');
var a='data-src';var e=document.querySelector('.un51');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-157-4.php');
var a='data-src';var e=document.querySelector('.un52');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-155-4.php');
var a='data-src';var e=document.querySelector('.un53');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-154-4.php');
var a='data-src';var e=document.querySelector('.un54');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-158-4.php');
var a='data-src';var e=document.querySelector('.un55');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-155-4.php');
var a='data-src';var e=document.querySelector('.un56');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-204-26.php':'images/transparentks-102-26.php');
var a='data-src';var e=document.querySelector('.un57');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-220-26.php':'images/k-stransparent-110-26.php');
var e=document.querySelector('.un33');e.setAttribute('src',(dpi>1)?'images/transparentks-128-26.php':'images/transparentks-64-26.php');
var e=document.querySelector('.un34');e.setAttribute('src',(dpi>1)?'images/k-stransparent-262-18.php':'images/k-stransparent-131-18.php');
var e=document.querySelector('.un35');e.setAttribute('src',(dpi>1)?'images/csi-logo-116-18.php':'images/csi-logo-58-18.php');
var e=document.querySelector('.un36');e.setAttribute('src',(dpi>1)?'images/preliminary_program_csi_2022-552-4.php':'images/preliminary_program_csi_2022-276-4.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
$('form').h5Validate();initMenu($('#m2')[0]);
$('.un203').mouseenter(function() { $.loadImages('images/preliminary_program_csi_2022-600-2.php', function() { }) });
$('.un203').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un203-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/preliminary_program_csi_2022-600-2.php'; } } });
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un183 source');ldsrcset('.un184 source');ldsrcset('.un185 source');ldsrcset('.un186 source');ldsrcset('.un187 source');ldsrcset('.un188 source');ldsrcset('.un189 source');ldsrcset('.un190 source');ldsrcset('.un191 source');ldsrcset('.un192 source');ldsrcset('.un193 source');ldsrcset('.un194 source');ldsrcset('.un195 source');ldsrcset('.un196 source');ldsrcset('.un197 source');ldsrcset('.un198 source');ldsrcset('.un199 source');ldsrcset('.un200 source');ldsrcset('.un201 source');ldsrcset('.un202 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}