(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-382.png':'images/transparentks-191.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-284.png':'images/transparentks-142-1.png');
var a='data-src';var e=document.querySelector('.un6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-284.png':'images/transparentks-142-1.png');
var a='data-src';var e=document.querySelector('.un7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/francerelance-314.png':'images/francerelance-157.png');
var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/bpi-252-1.png');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/frzanceactive-254-1.png');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/edstart-290.png':'images/edstart-145.png');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/lespremieres-382.png':'images/lespremieres-191.png');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/initiative-252-1.png');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/gbe-420.jpg':'images/gbe-210-1.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/feorange-322.png':'images/feorange-161.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-284.png':'images/transparentks-142-1.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848.png':'images/k-stransparent-424-1.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/transparentks-284.png':'images/transparentks-142-1.png');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/ks-conference-1912.png':'images/ks-conference-956.png');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-220.png':'images/transparentks-110.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-178.png':'images/transparentks-89.png');
var a='data-src';var e=document.querySelector('.un6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-178.png':'images/transparentks-89.png');
var a='data-src';var e=document.querySelector('.un7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/francerelance-194.png':'images/francerelance-97.png');
var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/bpi-314.png':'images/bpi-157.png');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/frzanceactive-318.png':'images/frzanceactive-159.png');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/edstart-182.png':'images/edstart-91.png');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/lespremieres-238.png':'images/lespremieres-119.png');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/initiative-314.png':'images/initiative-157.png');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/gbe-264.jpg':'images/gbe-132.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/feorange-190.png':'images/feorange-95.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-176.png':'images/transparentks-88.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530.png':'images/k-stransparent-265.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/transparentks-178.png':'images/transparentks-89.png');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/ks-conference-1200.png':'images/ks-conference-600.png');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-202.png':'images/transparentks-101.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-142.png':'images/transparentks-71.png');
var a='data-src';var e=document.querySelector('.un6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-142.png':'images/transparentks-71.png');
var a='data-src';var e=document.querySelector('.un7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/francerelance-156.png':'images/francerelance-78.png');
var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/bpi-252.png':'images/bpi-126.png');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/frzanceactive-254.png':'images/frzanceactive-127.png');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/edstart-146.png':'images/edstart-73.png');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/lespremieres-194.png':'images/lespremieres-97.png');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/initiative-252.png':'images/initiative-126.png');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/gbe-210.jpg':'images/gbe-105.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/feorange-160.png':'images/feorange-80.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-142.png':'images/transparentks-71.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-424.png':'images/k-stransparent-212.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/transparentks-142.png':'images/transparentks-71.png');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/ks-conference-866.png':'images/ks-conference-433.png');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-162.png':'images/transparentks-81.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-114-1.png':'images/transparentks-57-1.png');
var a='data-src';var e=document.querySelector('.un6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-114-1.png':'images/transparentks-57-1.png');
var a='data-src';var e=document.querySelector('.un7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/francerelance-126-2.png':'images/francerelance-63-1.png');
var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/bpi-202.png':'images/bpi-101.png');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/frzanceactive-202.png':'images/frzanceactive-101.png');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/edstart-116.png':'images/edstart-58.png');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/lespremieres-152.png':'images/lespremieres-76.png');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/initiative-202.png':'images/initiative-101.png');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/gbe-168-1.jpg':'images/gbe-84-1.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/feorange-128.png':'images/feorange-64.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-114.png':'images/transparentks-57.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-340.png':'images/k-stransparent-170.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/transparentks-114.png':'images/transparentks-57.png');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/ks-conference-692.png':'images/ks-conference-346.png');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-252.png':'images/transparentks-126.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-252.png':'images/transparentks-126.png');
var a='data-src';var e=document.querySelector('.un6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-252-1.png':'images/transparentks-126-1.png');
var a='data-src';var e=document.querySelector('.un7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/francerelance-378.png':'images/francerelance-189.png');
var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/bpi-424.png':'images/bpi-212.png');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/frzanceactive-273.png');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/edstart-350.png':'images/edstart-175.png');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/lespremieres-400.png':'images/lespremieres-200.png');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/initiative-313.png');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/gbe-434.jpg':'images/gbe-217.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/feorange-250.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-306.png':'images/transparentks-153.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-330.png':'images/k-stransparent-165.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/transparentks-192.png':'images/transparentks-96.png');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/ks-conference-942.png':'images/ks-conference-471.png');}else{var a='data-src';var e=document.querySelector('.un4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-168.png':'images/transparentks-84.png');
var a='data-src';var e=document.querySelector('.un5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-168.png':'images/transparentks-84.png');
var a='data-src';var e=document.querySelector('.un6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-168-1.png':'images/transparentks-84-1.png');
var a='data-src';var e=document.querySelector('.un7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/francerelance-252.png':'images/francerelance-126.png');
var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/bpi-280.png':'images/bpi-140.png');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/frzanceactive-366.png':'images/frzanceactive-183.png');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/edstart-234.png':'images/edstart-117.png');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/lespremieres-266.png':'images/lespremieres-133.png');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/initiative-416.png':'images/initiative-208.png');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/gbe-288.jpg':'images/gbe-144.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/feorange-334.png':'images/feorange-167.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-204.png':'images/transparentks-102.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-220.png':'images/k-stransparent-110.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/transparentks-128.png':'images/transparentks-64.png');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/ks-conference-628.png':'images/ks-conference-314.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un2=new Plyr('.un2 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un2.volume=0.8;
un2.on('enterfullscreen',function(){pop.hide('popup1');});un2.on('exitfullscreen',function(){pop.show('popup1');});pop.addHook('popup1',null,function(){un2.stop()});initMenu($('#m1')[0]);
initMenu($('#m2')[0]);
initMenu($('#m3')[0]);
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un97 source');ldsrcset('.un98 source');ldsrcset('.un99 source');ldsrcset('.un100 source');ldsrcset('.un101 source');ldsrcset('.un102 source');ldsrcset('.un103 source');ldsrcset('.un104 source');ldsrcset('.un105 source');ldsrcset('.un106 source');ldsrcset('.un107 source');ldsrcset('.un108 source');ldsrcset('.un109 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}