(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un249');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-284.png':'images/transparentks-142-1.png');
var a='data-src';var e=document.querySelector('.un250');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848.png':'images/k-stransparent-424-1.png');
var e=document.querySelector('.un248');e.setAttribute('src',(dpi>1)?'images/transparentks-284.png':'images/transparentks-142-1.png');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un249');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-178-1.png':'images/transparentks-89-1.png');
var a='data-src';var e=document.querySelector('.un250');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-1.png':'images/k-stransparent-265-1.png');
var e=document.querySelector('.un248');e.setAttribute('src',(dpi>1)?'images/transparentks-178.png':'images/transparentks-89.png');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un249');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-142.png':'images/transparentks-71.png');
var a='data-src';var e=document.querySelector('.un250');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-424.png':'images/k-stransparent-212.png');
var e=document.querySelector('.un248');e.setAttribute('src',(dpi>1)?'images/transparentks-142.png':'images/transparentks-71.png');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un249');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-114.png':'images/transparentks-57.png');
var a='data-src';var e=document.querySelector('.un250');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-340.png':'images/k-stransparent-170.png');
var e=document.querySelector('.un248');e.setAttribute('src',(dpi>1)?'images/transparentks-114.png':'images/transparentks-57.png');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un249');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-306.png':'images/transparentks-153.png');
var a='data-src';var e=document.querySelector('.un250');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-330.png':'images/k-stransparent-165.png');
var e=document.querySelector('.un248');e.setAttribute('src',(dpi>1)?'images/transparentks-192.png':'images/transparentks-96.png');}else{var a='data-src';var e=document.querySelector('.un249');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/transparentks-204.png':'images/transparentks-102.png');
var a='data-src';var e=document.querySelector('.un250');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-220.png':'images/k-stransparent-110.png');
var e=document.querySelector('.un248');e.setAttribute('src',(dpi>1)?'images/transparentks-128.png':'images/transparentks-64.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
initMenu($('#m22')[0]);
initMenu($('#m23')[0]);
initMenu($('#m24')[0]);
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un266 source');ldsrcset('.un267 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}